### ISSUE TITLE
Permissive License

### ISSUE THREAD

**Issue by sirinath** [NectarJS/nectarjs#128]
Is it possible to transition to a more permissive licenses from https://copyfree.org/ or AL2.0

**Comment by adrien-thierry** [comment]
Hi @sirinath ,

We are thinking about this, with a bigger community it could be easier

**Comment by GitGangGuy** [comment]
I'm visiting this project for the first time, thought I'd join in on the license wars: GPL/Free Software is great. It protects NectarJS from being integrated into some large proprietary codebase and ensures credit to its contributors. Imagine some corporation extends NectarJS and makes it proprietary and this community project ends up dying out and everyone pays license fees. For more reasoning, see [cuck licenses](https://lukesmith.xyz/articles/cucklicenses).

**Comment by adrien-thierry** [comment]
Hi @GitGangGuy , thx for your feedback

**Comment by wwderw** [comment]
Something that is more permissive with just the "runtime" use would help mitigate @GitGangGuy concerns while still being more permissive for those that use it "as is".  Or something with a linking exception.

Free as in FREEdom to me means being able to use it for whatever purpose you want, even for proprietary use cases.

I tend to do things in both spheres, so I can see both sides, but I prefer to have the option to use how I would want without having to worry.

I check in on this project from time to time, and since I don't usually change the core project itself in whatever framework I use (I just know enough to cause damage), usually it's whatever the resulting file(s) is what concerns me the most and how I can use those.  That's why I tend to favor MIT licensed frameworks or at the most restrictive that I like to use are LGPL version 2.

To me, as long as I can use the results of what the framework gives me without concern, that's the key thing for me.  I tend to favor the more permissive licenses as those are fairly straight forward with how things are handled.  Licenses like version 3 of the LGPL and GPL are just not that way.

**Comment by adrien-thierry** [comment]
@wwderw yes, it's a good idea

**Comment by adrien-thierry** [comment]
Moved to MIT
