### ISSUE TITLE
Cannot compile due to quotes error

### ISSUE THREAD

**Issue by Igorgro** [NectarJS/nectarjs#63]
When I'm trying to compile any js file, I'm getting tons of the following errors:
```
[error] Strings must use doublequote. line 1 column 27 in file ./index.js
```
My OS is Debian, Node.js v12.16.

**Comment by adrien-thierry** [comment]
Hi @Igorgro ,

For now, we force double quote in NectarJS to simplify transpilation / compilation,

We will need to add a babel visitor that convert all simple quotes in double quotes, adding escape etc

Ex: 
`var a = 'double quote in simple quote: " '`

Should become : 
`var a = "double quote in simple quote: \" "`

You can try to compile your code by using doubles quote instead of simple quotes

**Comment by Igorgro** [comment]
If i replace single quotes with double ones in **my** code, then it shows the same errors for all js files in node_modules. I cannot rewrite all used libraries to use double quotes.

**Comment by adrien-thierry** [comment]
yes right, i will add a visitor to convert everything

**Comment by adrien-thierry** [comment]
I added the visitor to convert single quotes to double quotes, can you test it ?

**Comment by Igorgro** [comment]
Yes, i've tested. I've tried to compile the following sample code:
```javascript
console.log('Hello, world');
```
It compiles successfully, but the output of execution of resulting binary is quite disappointing: it prints `1869769828`.

**Comment by adrien-thierry** [comment]
@Igorgro thx corrected, the visitor wasn't changing the string parameters, i will push the correction

**Comment by adrien-thierry** [comment]
Should be corrected

**Comment by Igorgro** [comment]
Yes, it fixed. Thanks.
